### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by roboflank**

### CODE REVIEW

**Comment by roboflank** [comment]
Will Add the code for the backend in a while

**Comment by TheBeachMaster** [comment]
Lots of changes in the UI looks like it... Will test it out 💪

**Comment by TheBeachMaster** [comment]
XDK can't configure the Bower packages... Revert?

**Comment by roboflank** [comment]
Don't revert,
Do bower install

**Comment by roboflank** [comment]
If you don't have bower install, just install it

**Comment by TheBeachMaster** [comment]
Ayayayaya.... Installed Bower... and stuff still messed up.... ati bower.json is not available.... And just cd'ed to that dir.... Damn it :(

**Comment by TheBeachMaster** [comment]
Intel XDK just removed the .xdk files... So, we're pretty much screwed thus far

**Pull request merged**
